name: Release
on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Log PWD
        run: pwd
      - name: List files
        run: ls -al
      - name: List files in parent directory
        run: ls -al ..
      - name: Check for Release
        run: node check-release.js